-- CREATING DATABSE
CREATE DATABASE ASSIGNMENT9;
USE ASSIGNMENT9;

-- CREATING TABLE
CREATE TABLE WORKER
(
WORKER_ID INT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME CHAR(25),
LAST_NAME CHAR(25),
SALARY INT (15),
JOINING_DATE DATE,
DEPARTMENT CHAR(25)
);
SELECT * FROM WORKER;

-- INSERTING VALUES
INSERT INTO WORKER
VALUES
(DEFAULT, 'HONEY','ROSE', '35000', '2021-03-10', 'IT'),
(DEFAULT, 'JANE','DOE', '45000', '2021-03-19', 'HR'),
(DEFAULT, 'ALICE','PHILIP', '55000', '2022-08-10', 'SECURITY'),
(DEFAULT, 'JHONE','MARKOSE', '15000', '2023-03-18', 'ADMIN'),
(DEFAULT, 'PALAK','SHARMA', '35000', '2024-05-10', 'IT'),
(DEFAULT, 'VIVIAAN','KAPOOR', '50000', '2025-01-10', 'ACCOUNTS'),
(DEFAULT, 'VIKRAM','BELLA', '55000', '2021-03-10', 'ACCOUNTS');
SELECT * FROM WORKER;

#1. STORED PROCEDURE THAT TAKES IN PARAMETERS FOR ALL COLUMNS AND ADDS A NEW RECORD TO THE TABLE AND INVOKES THE PROCEDURE CALL

DELIMITER //
CREATE PROCEDURE GETWORKER( IN DEPARTMENT_NAME VARCHAR(50))
BEGIN
SELECT W. FIRST_NAME, W.SALARY,W.DEPARTMENT FROM WORKER W WHERE W.DEPARTMENT = DEPARTMENT_NAME ;
END //
DELIMITER ;

CALL GETWORKER ('IT') ;

#2.WRITE A STORED PROCEDURE TAKES IN PARAMETER FOR WORKER_ID AND AN OUT PARAMETER FOR SALARY.

DELIMITER //
CREATE PROCEDURE SALARYBYWORKERID ( IN P_WORKER_ID INT, OUT P_SALARY INT (15))
BEGIN
SELECT SALARY INTO P_SALARY FROM WORKER
WHERE WORKER_ID = P_WORKER_ID ;
END //
DELIMITER ;

SET @SALARYOUTPUT = 0;
CALL SALARYBYWORKERID (1, @SALARYOUTPUT);
SELECT @SALARYOUTPUT AS SALARY;

#3. STORED PROCEDURE THAT TAKES IN PARAMETERS FOR WORKER_ID AND AN OUT PARAMETERS FOR DEPARTMENT

DELIMITER //
CREATE PROCEDURE GETDEPARTMENTBYWORKERID ( IN P_WORKER_ID INT, OUT P_DEPARTMENT VARCHAR(100))
BEGIN
SELECT DEPARTMENT INTO P_DEPARTMENT FROM WORKER
WHERE WORKER_ID = P_WORKER_ID ;
END //
DELIMITER ;

SET @DEPARTMENT_OUTPUT = 0;
CALL GETDEPARTMENTBYWORKERID (3, @DEPARTMENT_OUTPUT);
SELECT @DEPARTMENT_OUTPUT AS DEPARTMENT ;

#4. STORED PROCEDURE THAT TAKES IN PARAMETER FOR DEPARTMENT AND OUT PARAMETER FOR P_WORKER_COUNT

DELIMITER //
CREATE PROCEDURE GetWorkerCountByDepartment (IN P_DEPARTMENT VARCHAR(100), OUT P_WORKER_COUNT INT)
BEGIN
SELECT COUNT(*) INTO P_WORKER_COUNT FROM WORKER
WHERE DEPARTMENT = P_DEPARTMENT ;
END //
DELIMITER ;

SET @WORKERCOUNT_OUTPUT = 0;
CALL GetWorkerCountByDepartment ('IT', @WORKERCOUNT_OUTPUT);
SELECT @WORKERCOUNT_OUTPUT AS WORKER_COUNT;

#5. STORED PROCEDURE THAT TAKES IN PARAMETER FOR DEPARTMENT AND OUT PARAMETER FOR P_AVG_SALARY

DELIMITER //
CREATE PROCEDURE GetAvgSalaryByDepartment (IN P_DEPARTMENT VARCHAR(100), OUT P_AVG_SALARY INT(15))
BEGIN
SELECT avg(SALARY) INTO P_AVG_SALARY FROM WORKER
WHERE DEPARTMENT = P_DEPARTMENT ;
END //
DELIMITER ;

SET @AVGSALARY_OUTPUT = 0;
CALL GetAvgSalaryByDepartment ('ACCOUNTS', @AVGSALARY_OUTPUT);
SELECT @AVGSALARY_OUTPUT AS AVERAGE_SALARY;